development:
  adapter: postgresql
  encoding: unicode
  database: dcbknrljjb5cdk
  pool: 5
  username: xelgbgoixgallm
  password: 8fAFb8ZgZxdUcizKgsI2rAYCq9
  host: ec2-54-197-251-18.compute-1.amazonaws.com
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  username: action
  password:
  host: localhost
  port: 5432


production:
  adapter: postgresql
  encoding: unicode
  database: blog_production
  pool: 5
  username: action
  password:
  host: localhost
  port: 5432